udp_bridge/remotes/robot/name: echo

project11/platforms/echo:
  robot_description: echo/robot_description
  width: 0.5
  length: 2.0
  nav_sources:
    combined:
      position_topic: /echo/sensors/sbg/imu/nav_sat_fix
      orientation_topic: /echo/sensors/sbg/imu/data
      velocity_topic: /echo/sensors/sbg/imu/velocity