udp_bridge/remotes/robot/name: echo

project11/platforms/echo:
  robot_description: echo/robot_description
  width: 0.5
  length: 2.0
  nav_sources:
    combined:
      position_topic: /echo/project11/nav/position
      orientation_topic: /echo/project11/nav/orientation
      velocity_topic: /echo/project11/nav/velocity