mru_transform/sensors:
 - name: mru
   topics: { position: 'sensors/mru/position', orientation: 'sensors/mru/orientation', velocity: 'sensors/mru/velocity'}
      
helm_manager/output_type: 'twist'
helm_manager/twist/max_speed: 2.75
helm_manager/twist/max_yaw_speed: 0.5

navigator:
  robot:
    turn_radius: 5.0

    max_velocity:
      linear/x: 1.75

    default_velocity:
      linear/x: 1.5

  costmap:
    global_frame: echo/map
    robot_base_frame: echo/base_link
    transform_tolerance: 1.0