mru_transform/sensors:
 - name: mru
   topics: { position: 'mavros/global_position/global', orientation: 'mavros/imu/data', velocity: 'mavros/global_position/raw/gps_vel'}
      
helm_manager/output_type: 'twist'
helm_manager/twist/max_speed: 2.0
helm_manager/twist/max_yaw_speed: 1.5

mavros:
  conn/timesync_rate: 0.0
  global_position:
    tf/send: false
  local_position:
    tf/send: false

navigator:
  robot:
    turn_radius: 4.0

    max_velocity:
      linear/x: 2.0
      angular/z: 1.5

    default_velocity:
      linear/x: 1.5

    max_acceleration:
      linear/x: 0.75
      angular/z: 0.8

    default_acceleration:
      linear/x: 0.7
      angular/z: .3

    default_deceleration:
      linear/x: -0.35
      angular/z: -0.3

    max_deceleration:
      linear/x: -0.7
      angular/z: -0.8

    footprint: [[1.0, 0], [0.0, 0.3], [-0.5, 0.3], [-0.5, -0.3], [0.0, -0.3], [1.0, 0]]
    radius: 2.5

  costmap:
    global_frame: echo/map
    robot_base_frame: echo/base_link
    transform_tolerance: 1.0

  path_follower:
    pid:
      Kp: 20.0
      Ki: 0.5
      Kd: 0.6

s57_grids:
  map_frame: echo/map

  robot:
    frame_id: echo/base_link
    minimum_depth: 0.0
    maximum_caution_depth: 1.0
    overhead_clearance: 2.0
    minimum_speed: 0.01
    maximum_speed: 2.5

  grids:
    - name: local
      resolution: 3.0
      length: 5000.0
      period: 1.0

udp_bridge:
  remotes:
    operator:
      connections:
        default:
          topics:
            mavros_orientation: {source: mavros/imu/data}
            mavros_position: {source: mavros/global_position/global}
            mavros_velocity: {source: mavros/global_position/raw/gps_vel}
            
