udp_bridge/remotes/robot/name: echo

project11/platforms/echo:
  robot_description: echo/robot_description
  width: 0.5
  length: 2.0
  nav_sources:
    combined:
      position_topic: /echo/mavros/global_position/global
      orientation_topic: /echo/mavros/imu/data
      velocity_topic: /echo/mavros/global_position/raw/gps_vel