mru_transform/sensors:
 - name: mru
   topics: { position: 'mavros/global_position/global', orientation: 'mavros/imu/data', velocity: 'mavros/global_position/raw/gps_vel'}
      
helm_manager/output_type: 'twist'
helm_manager/twist/max_speed: 2.75
helm_manager/twist/max_yaw_speed: 0.5

navigator:
  robot:
    turn_radius: 5.0

    max_velocity:
      linear/x: 1.75

    default_velocity:
      linear/x: 1.5

  costmap:
    global_frame: echo/map
    robot_base_frame: echo/base_link
    transform_tolerance: 1.0

s57_grids:
  map_frame: echo/map

  robot:
    frame_id: echo/base_link
    minimum_depth: 0.0
    maximum_caution_depth: 1.0
    overhead_clearance: 2.0
    minimum_speed: 0.01
    maximum_speed: 2.5

  grids:
    - name: area
      resolution: 6.0
      length: 15000.0
      period: 30.0
    - name: local
      resolution: 3.0
      length: 5000.0
      period: 1.0

udp_bridge:
  remotes:
    operator:
      connections:
        default:
          topics:
            mavros_orientation: {source: mavros/imu/data}
            mavros_position: {source: mavros/global_position/global}
            mavros_velocity: {source: mavros/global_position/raw/gps_vel}
            
